import Head from 'next/head'
import styles from '../styles/Home.module.scss'


export default function Home() {

    return (
        <div >
            <Head>
                <title>Weather Forecast</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.container}>open</div>
        </div>
    )
}